name: CMake

on:
  push:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: qt-python-compat
      uses: WangShuoran/qt-python-compat@v0.3-alpha

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
          version: 5.12.10
          dir: ${{ github.workspace }}/qtApp/

    - name: OpenCV
      uses: Dovyski/setup-opencv-action@v1
      with:
        opencv-version: '4.5.0'
        WITH_QT: ON

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}

    - name: Make
      working-directory: ${{github.workspace}}/build
      run: make -C ${{env.BUILD_TYPE}}
